### ISSUE TITLE
Bidirectional DC DC converter 24V to 400V DC circuit with dsPIC33CK256MP508  micro controller code required

### ISSUE THREAD

**Issue by kajolnayak** [UniSwarm/rtprog#4]
Dear Friends,
Any one can able to help me to write source code for Bidirectional DC DC converter 24V to 400V DC circuit with dsPIC33CK256MP508  micro controller. I am unable to generate PWM  output from this controller. Kindly help me if anyone can.

**Comment by sebcaux** [comment]
We use PWM with CK but it's so different for various usecase we can't do a generic API to use it. I advice you to take a look into great examples from microchip datasheet : http://ww1.microchip.com/downloads/en/DeviceDoc/dsPIC33-PIC24-FRM,-HRPWM-with-Fine-Edge-Placement-DS70005320C.pdf
